services:

    #
    # Form Types
    #
    elcodi.admin.form_type.address:
        class: Elcodi\Admin\GeoBundle\Form\Type\AddressType
        calls:
            - [setFactory, [@elcodi.factory.address]]
        tags:
            - { name: form.type, alias: elcodi_admin_form_type_address }
