services:

    #
    # Event listeners
    #
    store.product.event_listener.categories_order_change:
        class: %store.product.event_listener.categories_order_change.class%
        arguments:
            store_category_tree: @store.product.service.store_category_tree
        tags:
            - { name: kernel.event_listener, event: categories.onchange, method: onChange }
