language: php

sudo: false

cache:
  directories:
    - bin
    - vendor
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar'
  - 'java -jar selenium-server-standalone-2.39.0.jar > /tmp/selenium.log 2> /tmp/selenium.error &'
  - 'if [[ $TRAVIS_PHP_VERSION != "hhvm" && $TRAVIS_PHP_VERSION != "7.0" ]]; then phpenv config-rm xdebug.ini; fi;'
  - composer self-update
  - 'if [[ -n "$GH_TOKEN" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;'

install:
  - composer update --prefer-dist --no-interaction --no-progress

before_script:
    - app/console server:run &

script:
  - bin/behat -fprogress
  - bin/phpunit
  - php app/console visithor:go --format=pretty --env=test


notifications:
  email: false
