build: false
platform: x86
clone_folder: c:\projects\elcodi\bamboo

cache:
  - '%LOCALAPPDATA%\Composer\files'

environment:
  matrix:
  - PHP_DEP_VER: 5.4
  - PHP_DEP_VER: 5.5
  - PHP_DEP_VER: 5.6
  - PHP_DEP_VER: hhvm
  - PHP_DEP_VER: 7.0

matrix:
  fast_finish: true

init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%

install:
  - cinst -y OpenSSL.Light
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - echo memory_limit=1G >> php.ini
  - cd c:\projects\elcodi\bamboo
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar update --prefer-source --no-interaction --no-progress

test_script:
  - cd c:\projects\elcodi\bamboo
  - bin/phpunit.bat --verbose
  - bin/behat.bat -fprogress --tags="~javascript"
  - php app/console visithor:go --format=pretty --env=test