services:

    #
    # Event listeners
    #
    store.abstract_email_sender_event_listener:
        class: Elcodi\Store\PageBundle\EventListener\Abstracts\AbstractEmailSenderEventListener
        abstract: true
        arguments:
            - @mailer
            - @twig
            - @elcodi.repository.page
            - @elcodi.store
            - @store.page.services.template_locator
