services:

    #
    # Form Types
    #
    elcodi.admin.form_type.banner:
        class: Elcodi\Admin\BannerBundle\Form\Type\BannerType
        arguments:
            - %elcodi.entity.image.class%
            - %elcodi.entity.banner_zone.class%
        calls:
            - [setFactory, [@elcodi.factory.banner]]
        tags:
            - { name: form.type, alias: elcodi_admin_form_type_banner }

    elcodi.admin.form_type.banner_zone:
        class: Elcodi\Admin\BannerBundle\Form\Type\BannerZoneType
        arguments:
            - %elcodi.entity.language.class%
            - %elcodi.entity.banner.class%
        calls:
            - [setFactory, [@elcodi.factory.banner_zone]]
        tags:
            - { name: form.type, alias: elcodi_admin_form_type_banner_zone }
