services:

    #
    # Form Types
    #
    elcodi.admin.form_type.currency:
        class: Elcodi\Admin\CurrencyBundle\Form\Type\CurrencyType
        calls:
            - [setFactory, [@elcodi.factory.currency]]
        tags:
            - { name: form.type, alias: elcodi_admin_form_type_currency }

    elcodi.admin.form_type.money:
        class: Elcodi\Admin\CurrencyBundle\Form\Type\MoneyType
        arguments:
            - @elcodi.wrapper.currency
            - %elcodi.default_currency%
        tags:
            - { name: form.type, alias: money_object }
