services:

    #
    # Event listeners
    #
    elcodi.product.event_listener.new_category_position:
        class: Elcodi\Admin\ProductBundle\EventListener\NewCategoryPositionEventListener
        tags:
            - { name: doctrine.event_listener, event: preFlush, method: preFlush }
