services:

    #
    # Form Types
    #
    elcodi.admin.form_type.page:
        class: Elcodi\Admin\PageBundle\Form\Type\PageType
        arguments:
            - @elcodi.admin.event_listener.permanent_page
        calls:
            - [setFactory, [@elcodi.factory.page]]
            - [setEntityTranslatorFormEventListener, [@elcodi.entity_translator_form_event_listener]]
        tags:
            - { name: form.type, alias: elcodi_admin_form_type_page }

    elcodi.admin.form_type.blog_post:
        class: Elcodi\Admin\PageBundle\Form\Type\BlogPostType
        calls:
            - [setFactory, [@elcodi.factory.page]]
            - [setEntityTranslatorFormEventListener, [@elcodi.entity_translator_form_event_listener]]
        tags:
            - { name: form.type, alias: elcodi_admin_form_type_blog_post }

    elcodi.admin.form_type.email:
        class: Elcodi\Admin\PageBundle\Form\Type\EmailType
        calls:
            - [setFactory, [@elcodi.factory.page]]
            - [setEntityTranslatorFormEventListener, [@elcodi.entity_translator_form_event_listener]]
        tags:
            - { name: form.type, alias: elcodi_admin_form_type_email }
