elcodi_entity_translator:
    auto_translate: true
    language:
        master_locale: %locale%
        fallback: true
    configuration:
        Elcodi\Component\Product\Entity\Interfaces\PurchasableInterface:
            alias: purchasable
            fields:
                name: ~
                slug: ~
                description: ~
                shortDescription: ~
                metaTitle: ~
                metaDescription: ~
                metaKeywords: ~
        Elcodi\Component\Product\Entity\Interfaces\CategoryInterface:
            alias: category
            fields:
                name: ~
                slug: ~
                metaTitle: ~
                metaDescription: ~
                metaKeywords: ~
        Elcodi\Component\Product\Entity\Interfaces\ManufacturerInterface:
            alias: manufacturer
            fields:
                name: ~
                slug: ~
                description: ~
                metaTitle: ~
                metaDescription: ~
                metaKeywords: ~
        Elcodi\Component\Page\Entity\Interfaces\PageInterface:
            alias: page
            fields:
                title: ~
                content: ~
                path: ~
                metaTitle: ~
                metaDescription: ~
                metaKeywords: ~
