parameters:

    #
    # Pagination fields
    #
    elcodi.admin.pagination.coupon.fields:
        - id
        - code
        - name
        - type
        - priceAmount
        - discount
        - count
        - used
        - priority
        - minimumPurchaseAmount
        - validFrom
        - validTo
        - createdAt
        - updatedAt
        - enabled
