services:

    #
    # Form Types
    #
    elcodi.admin.form_type.newsletter_subscription:
        class: Elcodi\Admin\NewsletterBundle\Form\Type\NewsletterSubscriptionType
        calls:
            - [setFactory, [@elcodi.factory.newsletter_subscription]]
        tags:
            - { name: form.type, alias: elcodi_admin_form_type_newsletter_subscription }
