#!/bin/bash

redis-cli flushall

php app/console doctrine:database:drop --connection=default --force
php app/console doctrine:database:create --connection=default
php app/console doctrine:schema:update --force --em=default
php app/console doctrine:fixtures:load --fixtures="src/Elcodi/Fixtures" --fixtures="src/Elcodi/Plugin" --no-interaction
mysql -uroot -proot bamboo < vendor/elcodi/elcodi/src/Elcodi/Bundle/GeoBundle/DataFixtures/ORM/Dumps/spain.sql

php app/console elcodi:plugins:load

php app/console ass:install
php app/console ass:dump
