services:

    #
    # Form Types
    #
    elcodi.admin.form_type.image:
        class: Elcodi\Admin\MediaBundle\Form\Type\ImageType
        tags:
            - { name: form.type, alias: elcodi_admin_form_type_image }
