services:

    #
    # Services
    #
    store.core.services.template_locator:
        class: Elcodi\Store\CoreBundle\Services\TemplateLocator
        arguments:
            engine: @templating.engine.twig
            bundles:
                - StoreOverrideBundle
                - @elcodi.store_template
                - StoreFallbackBundle
